### ISSUE TITLE
Portico WAN Support

### ISSUE THREAD

**Issue by timpokorny** [openlvc/portico#45]
Story
--------
**{As a}** federate operator,
**{I want}** to be able to connect to a federation over a WAN,
**{So that I can}** participate in exercises or experiments that are not running on my local network

Context
------------
Portico's current communications facilities use multicast to enable the efficient delivery of messages between large groups of federates. As multicast comms are blocked at the edge of the network, this has meant that for a federate to participate, it has to be on the same local network as the rest of the federation.

It has become increasingly common to run federations across geographically distributed areas, allowing more people to participate in an experiment or exercise without having to physically be present in the same location.

To support users wishing to run federations in this type of environment, enhancements to Portico are required to enable connection and communication across a WAN. This includes both single federates connecting into a central network, as well as enabling interoperation between clusters of federates located on different networks, where some federates are local while others are remote.

### Design Considerations
Supporting federations across a WAN involves considering a number of different topologies. From 1-1 federations, to those with a single external connection (1-Many), to those that involve clusters of federates running at various sites (Many-to-Many).

On approach is to put everyone on a VPN and rely on the lower level network facilities to provide the connection. Unfortunately this does require a significant amount of network-level configuration and is not something that would typically be supported by IT administration due to the blanket network access it provides.

A simple, native Portico facility is required. This solution must deal appropriately with Firewall and NAT Traversal issues, and be capable of supporting the deployment types described above.

### Requirements
The following high-level requirements are needed to complete this work:

  - Solution must support Firewall and NAT Traversal
  - Solution must enable Point-to-Point connections
    - A single federate joining a federation running on a LAN with one or more participants
  - Solution must enable Clustered Connections
    - Two networks connected which each have multiple local federates
  - Solution must enable Hybrid Federations
    - A combination of the two modes above - with single federates and networks of federates joining a single federation
  - Solution must work across Java and C++ Interfaces
    - Initial testing on 1516e federation

Acceptance Criteria
----------------------------
Once complete, I shall be able to:
  - [x] Connect a single federate into a federation running on another network
  - [x] Connect multiple federates running on a local network with a federation running on another separate local network
  - [x] Create hybrid federations with some federates are the only ones running on their local network and other local networks have many active federates
  - [x] Deploy the above facilities in environments that use Firewalls and NATs
  - [x] Deploy this facility whether using the Java or C++ interface

Stories and Tasks
--------------------------
  - #44 WAN Support for Single Federates
  - #46 WAN Support for Clustered Federations
  - #47 WAN Test Federate

**Comment by timpokorny** [comment]
Epic now complete. Bug fixes only expected from here on out.
